# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db150aa3a1e49dc4948e8603ac39d9cd63b8dd5a810bc0317b28411dbe211a128913dd3cc45ad02eb76a38d208c014321ed8b28aa53743bac4dcea34e31af889

test:
  secret_key_base: b13cc949c7c1f900e67f4f639140a5e3cdeefa7324e1b4e2a1c4b541463543f2e2d214c5485f93b39b6e42ada480109873f213c7641da8c0598d6e92de533e3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
